
const calStyles = {

  page: {
    minHeight: '100vh',
    background: '#f1f5f9',
  },

  navbar: {
    background: 'linear-gradient(135deg, #3b82f6, #2563eb)',
    padding: '0 32px',
    height: '60px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    boxShadow: '0 2px 12px rgba(59,130,246,0.30)',
  },
  navLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  navLogoBox: {
    width: '36px',
    height: '36px',
    background: 'rgba(255,255,255,0.20)',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navTitle: {
    color: '#ffffff',
    fontSize: '17px',
    fontWeight: '700',
  },
  navRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  navUser: {
    color: 'rgba(255,255,255,0.90)',
    fontSize: '14px',
    fontWeight: '500',
  },
  btnBack: {
    padding: '8px 18px',
    background: 'rgba(255,255,255,0.15)',
    color: '#ffffff',
    border: '1px solid rgba(255,255,255,0.30)',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    transition: 'background 0.2s',
  },

  content: {
    padding: '36px 40px',
    maxWidth: '1100px',
    margin: '0 auto',
  },
  layout: {
    display: 'grid',
    gridTemplateColumns: '380px 1fr',
    gap: '24px',
    alignItems: 'start',
  },

  calPanel: {
    background: '#ffffff',
    borderRadius: '16px',
    padding: '24px',
    border: '1px solid #e2e8f0',
    boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
  },
  calHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '12px',
  },
  navArrow: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    border: '1px solid #e2e8f0',
    background: '#f8fafc',
    color: '#475569',
    fontSize: '22px',
    cursor: 'pointer',
    display: 'grid',
    placeItems: 'center',
    lineHeight: 1,
  },
  calMonthLabel: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '2px',
  },
  calMonthName: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#0f172a',
  },
  calYear: {
    fontSize: '13px',
    color: '#64748b',
    fontWeight: '500',
  },
  todayBtn: {
    display: 'block',
    margin: '0 auto 16px',
    padding: '6px 18px',
    background: '#eff6ff',
    color: '#2563eb',
    border: '1px solid #bfdbfe',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: '600',
    cursor: 'pointer',
  },

  weekRow: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    marginBottom: '6px',
  },
  weekLabel: {
    textAlign: 'center',
    fontSize: '11px',
    fontWeight: '700',
    color: '#94a3b8',
    padding: '4px 0',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  daysGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gap: '4px',
  },
  dayCell: {
    aspectRatio: '1',
    borderRadius: '10px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'default',
    position: 'relative',
    gap: '2px',
  },
  dayCellActive: {
    cursor: 'pointer',
    transition: 'background 0.15s',
  },
  dayCellToday: {
    border: '2px solid #2563eb',
    background: '#eff6ff',
  },
  dayCellSelected: {
    background: '#2563eb',
    color: '#ffffff',
  },
  dayNum: {
    fontSize: '13px',
    fontWeight: '600',
    lineHeight: 1,
  },
  dotRow: {
    display: 'flex',
    gap: '3px',
  },
  dotBlue: {
    width: '5px',
    height: '5px',
    borderRadius: '50%',
    background: '#3b82f6',
    display: 'inline-block',
  },
  dotGreen: {
    width: '5px',
    height: '5px',
    borderRadius: '50%',
    background: '#22c55e',
    display: 'inline-block',
  },
  legend: {
    display: 'flex',
    gap: '16px',
    marginTop: '16px',
    paddingTop: '14px',
    borderTop: '1px solid #f1f5f9',
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    color: '#64748b',
  },

  detailPanel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  detailHeader: {
    background: '#ffffff',
    borderRadius: '12px',
    padding: '18px 24px',
    border: '1px solid #e2e8f0',
    boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
  },
  detailDateLabel: {
    fontSize: '17px',
    fontWeight: '700',
    color: '#0f172a',
    margin: 0,
  },
  detailSection: {
    background: '#ffffff',
    borderRadius: '12px',
    padding: '20px 24px',
    border: '1px solid #e2e8f0',
    boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
  },
  detailSectionTitle: {
    fontSize: '15px',
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: '14px',
    margin: '0 0 14px 0',
  },
  emptyText: {
    fontSize: '13px',
    color: '#94a3b8',
    margin: 0,
  },

  activityList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  activityCard: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: '12px',
    padding: '14px 16px',
    borderRadius: '10px',
    background: '#f8fafc',
    border: '1px solid #e2e8f0',
  },
  activityCardLeft: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
  },
  activityCardIcon: {
    fontSize: '22px',
    flexShrink: 0,
    lineHeight: 1,
    marginTop: '2px',
  },
  activityCardHabit: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#2563eb',
    margin: '0 0 2px 0',
  },
  activityCardText: {
    fontSize: '14px',
    color: '#0f172a',
    margin: '0 0 4px 0',
  },
  activityCardMotivo: {
    fontSize: '13px',
    color: '#047857',
    margin: '0 0 4px 0',
  },
  tagVence: {
    fontSize: '11px',
    color: '#b45309',
    background: '#fffbeb',
    borderRadius: '5px',
    padding: '2px 8px',
    border: '1px solid #fde68a',
    display: 'inline-block',
  },
  tagRecurrente: {
    fontSize: '11px',
    color: '#1d4ed8',
    background: '#eff6ff',
    borderRadius: '5px',
    padding: '2px 8px',
    border: '1px solid #bfdbfe',
    display: 'inline-block',
  },
  statusDone: {
    fontSize: '12px',
    fontWeight: '700',
    color: '#16a34a',
    background: '#f0fdf4',
    borderRadius: '8px',
    padding: '4px 10px',
    border: '1px solid #bbf7d0',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },
  statusPending: {
    fontSize: '12px',
    fontWeight: '700',
    color: '#b45309',
    background: '#fffbeb',
    borderRadius: '8px',
    padding: '4px 10px',
    border: '1px solid #fde68a',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },

  noteArea: {
    width: '100%',
    padding: '12px 14px',
    borderRadius: '10px',
    border: '1px solid #cbd5e1',
    fontSize: '14px',
    color: '#0f172a',
    resize: 'vertical',
    fontFamily: 'inherit',
    lineHeight: '1.6',
    boxSizing: 'border-box',
    outline: 'none',
    marginBottom: '12px',
    display: 'block',
  },
  btnSaveNote: {
    padding: '10px 20px',
    background: '#2563eb',
    color: '#ffffff',
    border: 'none',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '700',
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(37,99,235,0.25)',
  },
}

export default calStyles